import { getApps, getApp, initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, updateDoc, collection, getDocs, query, where, limit, onSnapshot, arrayUnion, deleteField } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

const config={apiKey:'AIzaSyB72y9YkdCifEodbo2g_43FbbcDbvg0Q4',authDomain:'oilanazorat-3c8de.firebaseapp.com',projectId:'oilanazorat-3c8de',storageBucket:'oilanazorat-3c8de.firebasestorage.app',messagingSenderId:'1086556994078',appId:'1:1086556994078:web:5e576984e784d0bbdc4c0f',measurementId:'G-NWER8TE97X'};
const app=getApps().length?getApp():initializeApp(config); const auth=getAuth(app); const db=getFirestore(app);
let startBtn,stopBtn,statusEl,requestUnsub,audioUnsub,peer,remoteAudio,fallbackTimer,audioContext,nextPlayTime=0,currentTarget,currentRequestId,currentSession; let legacy=false; const seen=new Set(); const childCandidates=new Set(); const parentCandidates=new Set();
function family(){return localStorage.getItem('family')}
async function child(){const f=family(),name=document.getElementById('childName')?.textContent?.trim();if(!f||!name)return null;const s=await getDocs(query(collection(db,'families',f,'children'),where('nomi','==',name),limit(1)));return s.empty?null:{family:f,id:s.docs[0].id}}
function refs(t){const b=['families',t.family,'children',t.id];return{request:doc(db,...b,'mic_requests','current'),audio:collection(db,...b,'mic_audio')}}
function status(t){if(statusEl)statusEl.textContent=t}
function servers(){return[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]}
async function start(){if(!startBtn||startBtn.disabled)return;startBtn.disabled=true;legacy=false;currentTarget=await child();if(!currentTarget){status('❌ Farzand qurilmasi aniqlanmadi');startBtn.disabled=false;return}const u=auth.currentUser;if(!u){status('❌ Avval ota-ona paneliga kiring');startBtn.disabled=false;return}const p=await getDoc(doc(db,'parents',u.uid));if(!p.exists()){status('❌ Ota-ona profili topilmadi');startBtn.disabled=false;return}const r=refs(currentTarget);currentRequestId=`mic_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;currentSession=null;seen.clear();childCandidates.clear();parentCandidates.clear();requestUnsub=onSnapshot(r.request,async s=>{const d=s.data()||{};if(d.requestId!==currentRequestId)return;if(d.status==='active'&&d.transport==='webrtc'&&d.webrtcAnswer&&peer&&!peer.currentRemoteDescription){try{await peer.setRemoteDescription({type:'answer',sdp:d.webrtcAnswer});status('🔴 Jonli ovoz')}catch(_){fallback('WebRTC javobi qabul qilinmadi')}}if(d.status==='active'&&legacy&&d.sessionId){currentSession=d.sessionId;attachLegacy(r.audio,d.sessionId);status('🔴 Jonli ovoz')}if(d.status==='failed'&&d.transport==='webrtc'&&!legacy)fallback(d.error||'WebRTC xatosi');if(d.status==='stopped'){status('To‘xtatildi');cleanup(true)}if(peer&&d.childCandidates)await candidates(d.childCandidates)},e=>status(`❌ ${e.message||'Ulanish xatosi'}`));try{await webRtc(r)}catch(e){fallback(e.message||'WebRTC xatosi')}}
async function webRtc(r){peer=new RTCPeerConnection({iceServers:servers()});remoteAudio=document.createElement('audio');remoteAudio.autoplay=true;remoteAudio.playsInline=true;remoteAudio.style.display='none';document.body.appendChild(remoteAudio);peer.ontrack=e=>{remoteAudio.srcObject=e.streams?.[0]||new MediaStream([e.track]);remoteAudio.play().catch(()=>status('🔴 Jonli ovoz — oynaga bosing'))};peer.onicecandidate=e=>{if(!e.candidate)return;const c=e.candidate;if(parentCandidates.has(c.candidate))return;parentCandidates.add(c.candidate);updateDoc(r.request,{parentCandidates:arrayUnion({candidate:c.candidate,sdpMid:c.sdpMid,sdpMLineIndex:c.sdpMLineIndex})}).catch(()=>{})};peer.onconnectionstatechange=()=>{if(peer?.connectionState==='connected'){clearTimeout(fallbackTimer);status('🔴 Jonli ovoz')}else if(peer?.connectionState==='failed')fallback('WebRTC tarmoq ulanishi ishlamadi')};peer.addTransceiver('audio',{direction:'recvonly'});await setDoc(r.request,{requestId:currentRequestId,status:'webrtc_requested',transport:'webrtc',requestedByUid:auth.currentUser.uid,requestedAt:Date.now(),updatedAt:Date.now(),webrtcOffer:deleteField(),webrtcAnswer:deleteField(),parentCandidates:[],childCandidates:[]},{merge:true});const offer=await peer.createOffer();await peer.setLocalDescription(offer);await updateDoc(r.request,{webrtcOffer:offer.sdp,updatedAt:Date.now()});fallbackTimer=setTimeout(()=>{if(peer&&peer.connectionState!=='connected')fallback('WebRTC ulanishi vaqt oldi')},9000)}
async function candidates(list){for(const x of list||[]){if(!x?.candidate||childCandidates.has(x.candidate))continue;childCandidates.add(x.candidate);try{await peer.addIceCandidate(new RTCIceCandidate(x))}catch(_) {}}}
function attachLegacy(audio,session){audioUnsub?.();audioUnsub=onSnapshot(query(audio,where('sessionId','==',session)),s=>{s.docChanges().forEach(ch=>{if(ch.type!=='added')return;const d=ch.doc.data(),n=Number(d.sequence??-1);if(n<0||seen.has(n))return;seen.add(n);const b=d.audio?.toUint8Array?.();if(!b)return;if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});const samples=new Int16Array(b.buffer,b.byteOffset,Math.floor(b.byteLength/2));const buf=audioContext.createBuffer(1,samples.length,16000),c=buf.getChannelData(0);for(let i=0;i<samples.length;i++)c[i]=samples[i]/32768;const src=audioContext.createBufferSource();src.buffer=buf;src.connect(audioContext.destination);const when=Math.max(audioContext.currentTime+.01,nextPlayTime||audioContext.currentTime+.08);src.start(when);nextPlayTime=when+buf.duration})},()=>status('❌ Zaxira ovoz oqimi xatosi'))}
async function fallback(reason){if(legacy||!currentTarget||!currentRequestId)return;legacy=true;clearTimeout(fallbackTimer);status('⏳ WebRTC ulanmagan — zaxira ovoz kanali ishga tushmoqda…');try{await cleanupPeer();const r=refs(currentTarget);await updateDoc(r.request,{status:'requested',transport:'legacy',updatedAt:Date.now(),webrtcOffer:deleteField(),webrtcAnswer:deleteField(),parentCandidates:[],childCandidates:[]});status('⏳ Bola qurilmasidan kutilmoqda…')}catch(_){status(`❌ ${reason||'Ovoz ulanmagan'}`);startBtn.disabled=false}}
async function stop(){if(!currentTarget)currentTarget=await child();try{if(currentTarget)await updateDoc(refs(currentTarget).request,{status:'stop_requested',updatedAt:Date.now()})}catch(_){}status('⏳ To‘xtatilmoqda…');stopBtn.disabled=true;await cleanup(true)}
async function cleanupPeer(){clearTimeout(fallbackTimer);try{peer?.close()}catch(_){}peer=null;if(remoteAudio){remoteAudio.srcObject=null;remoteAudio.remove();remoteAudio=null}}
async function cleanup(close){requestUnsub?.();requestUnsub=null;audioUnsub?.();audioUnsub=null;await cleanupPeer();currentTarget=null;currentRequestId=null;currentSession=null;seen.clear();if(close&&audioContext){await audioContext.close().catch(()=>{});audioContext=null}nextPlayTime=0;if(startBtn)startBtn.disabled=false;if(stopBtn)stopBtn.disabled=true}
function bind(){startBtn=document.getElementById('micStart');stopBtn=document.getElementById('micStop');statusEl=document.getElementById('micStatus');if(!startBtn||!stopBtn||!statusEl)return;startBtn.onclick=start;stopBtn.onclick=stop}
const timer=setInterval(()=>{bind();if(startBtn&&stopBtn&&statusEl)clearInterval(timer)},300);setTimeout(bind,700);
