import{getApps,initializeApp,getApp}from'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import{getFirestore,collection,query,where,getDocs,doc,getDoc,setDoc,deleteDoc}from'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

const cfg={apiKey:'AIzaSyB72y9YkdCifEodbo2g_43FbbcDbvg0QF4',authDomain:'oilanazorat-3c8de.firebaseapp.com',projectId:'oilanazorat-3c8de',storageBucket:'oilanazorat-3c8de.firebasestorage.app',messagingSenderId:'1086556994078',appId:'1:1086556994078:web:5e576984e784d0bbdc4c0f'};
const app=getApps().length?getApp():initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
let booted=false,isPremium=false,ownedFamilies=[];
const style=document.createElement('style');style.textContent=`#loginBtn{display:none!important}.pwa-family{margin-top:14px}.pwa-family .family-card{border:1px solid #e1e6ee;background:#fff;border-radius:16px;padding:15px;margin:9px 0}.pwa-family .family-card b{display:block;font-size:15px}.pwa-family .family-card small{display:block;color:#8993a2;margin:4px 0 10px}.pwa-family .family-card button,.pwa-family .secondary{width:100%;border:0;border-radius:12px;padding:12px;font-weight:850}.pwa-family .family-card button{background:#111827;color:#fff}.pwa-family .secondary{background:#eef2ff;color:#3856a8;margin-top:8px}.pwa-family .codebox{font-size:22px;letter-spacing:.16em;text-align:center;background:#f5f7fb;border:1px dashed #9aa7b8;border-radius:14px;padding:14px;margin:10px 0;font-weight:900}.pwa-family .premium-box{border:1px solid #ead7a0;background:#fff9e8;border-radius:16px;padding:15px;margin-top:12px}.pwa-family .premium-box b{display:block}.pwa-family .premium-box p{margin:6px 0;color:#6b5a2a;font-size:13px;line-height:1.5}.child-unlink{margin-left:auto;flex:0 0 44px;width:44px;height:44px;border:0;border-radius:12px;background:#fff1f1;color:#dc2626;font-size:19px;font-weight:900;display:grid;place-items:center;cursor:pointer}.child-unlink:disabled{opacity:.5}`;document.head.appendChild(style);
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function makeCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<6;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s}
function openFamily(code){sessionStorage.setItem('family',code);location.reload()}
function panel(){return $('codeScreen')?.querySelector('.card')}
async function loadPlan(){const u=auth.currentUser;if(!u)return false;try{const p=await getDoc(doc(db,'parents',u.uid));isPremium=p.getBoolean('premium')===true;const s=await getDocs(query(collection(db,'families'),where('ownerUid','==',u.uid)));ownedFamilies=s.docs;return true}catch(e){console.error(e);isPremium=false;ownedFamilies=[];return false}}
function premiumMessage(){return`<div class="premium-box"><b>⭐ Premium kerak</b><p>Free tarifda 1 ta oila kodi va 1 ta faol farzand bilan cheklangan. Premium orqali bir nechta oilani saqlash, har bir oilaga bir nechta Android qurilmasini ulash va eski oila kodlarini yo‘qotmasdan boshqarish mumkin.</p><button id="premiumInfo" class="secondary">Premiumni faollashtirish</button></div>`}
function render(){const card=panel();if(!card)return;if(booted)return;booted=true;card.innerHTML=`<h2>Oila kodi</h2><p class="muted">Google hisobingizga ulangan oilalar avtomatik ko‘rsatiladi.</p><div id="pwaFamilies" class="pwa-family"><div class="loading">Tarif va oilalar tekshirilmoqda…</div></div>`;renderFamilies()}
async function renderFamilies(){const box=$('pwaFamilies');if(!box)return;const u=auth.currentUser;if(!u)return;box.innerHTML='<div class="loading">Mavjud oilalar yuklanmoqda…</div>';await loadPlan();let html=`<button id="createFamily" class="primary">➕ Yangi oila kodi yaratish${isPremium?'':' 🔒'}</button><button id="joinFamily" class="secondary">🔗 Mavjud oila kodini kiritish</button><div id="familyList" class="pwa-family"></div>`;if(!isPremium&&ownedFamilies.length>=1)html+=premiumMessage();box.innerHTML=html;$('createFamily').onclick=createFamily;$('joinFamily').onclick=()=>{if(!isPremium&&ownedFamilies.length>=1){showPremium();return}box.innerHTML=`<h3>Mavjud oila kodi</h3><p class="muted">Android farzand qurilmasi ulangan oila kodini kiriting.</p><input id="pwaCode" class="code" maxlength="20" autocomplete="off" autocapitalize="characters" placeholder="AB12CD"><button id="pwaJoin" class="primary">Davom etish</button><p id="pwaErr" class="err"></p><button id="pwaBack" class="secondary">← Orqaga</button>`;$('pwaJoin').onclick=joinFamily;$('pwaBack').onclick=()=>renderFamilies()};if($('premiumInfo'))$('premiumInfo').onclick=showPremium;const list=$('familyList');if(ownedFamilies.length===0){list.innerHTML='<div class="empty">Hali sizga tegishli oila yaratilmagan.<br>Yuqoridagi tugma orqali yangi kod yarating.</div>'}else{list.innerHTML=`<h3 style="margin:18px 0 8px">Mening oilalarim ${isPremium?'⭐ Premium':'(Free)'}</h3>`;ownedFamilies.forEach(d=>{const el=document.createElement('div');el.className='family-card';el.innerHTML=`<b>Oila kodi: ${esc(d.id)}</b><small>Saqlangan oila · Farzandlar bilan bog‘langan</small><button>Oila panelini ochish →</button>`;el.querySelector('button').onclick=()=>openFamily(d.id);list.appendChild(el)})}}
function showPremium(){const box=$('pwaFamilies');if(!box)return;box.innerHTML=premiumMessage()+`<button id="premiumBack" class="secondary">← Orqaga</button>`;if($('premiumInfo'))$('premiumInfo').onclick=showPremium;if($('premiumBack'))$('premiumBack').onclick=renderFamilies}
async function createFamily(){const u=auth.currentUser;if(!u)return;await loadPlan();if(!isPremium&&ownedFamilies.length>=1){showPremium();return}const b=$('createFamily');if(b)b.disabled=true;for(let i=0;i<8;i++){const code=makeCode();try{const ref=doc(db,'families',code),old=await getDoc(ref);if(old.exists())continue;await setDoc(ref,{ownerUid:u.uid,yaratilganMs:Date.now(),premium:isPremium});sessionStorage.setItem('family',code);const box=$('pwaFamilies');box.innerHTML=`<div class="family-card"><b>🎉 Yangi oila yaratildi</b><div class="codebox">${code}</div><small>Farzandingizning Android qurilmasida shu kod orqali oilaga ulang. ${isPremium?'Premium: bu oila saqlanib qoladi va boshqa oilalar bilan birga boshqariladi.':'Free tarif: bu sizning yagona oilangiz.'}</small><button id="openCreated">Farzandlarni ko‘rish →</button></div>`;$('openCreated').onclick=()=>location.reload();return}catch(e){console.error(e);if(b)b.disabled=false;box.innerHTML='<p class="err">Oila yaratilmadi: '+esc(e.message||'Firebase xatosi')+'</p><button class="primary" id="retryFamily">Qayta urinish</button>';if($('retryFamily'))$('retryFamily').onclick=createFamily;return}}if(b)b.disabled=false}
async function joinFamily(){const c=($('pwaCode')?.value||'').trim().toUpperCase(),err=$('pwaErr');if(!c){err.textContent='Oila kodini kiriting.';return}try{await loadPlan();const s=await getDoc(doc(db,'families',c));if(!s.exists()){err.textContent='Oila kodi topilmadi.';return}const owner=s.data().ownerUid;if(owner&&owner!==auth.currentUser.uid){err.textContent='Bu oila kodi boshqa ota-onaga tegishli.';return}if(!isPremium&&ownedFamilies.length>=1&&!ownedFamilies.some(d=>d.id===c)){err.textContent='Free tarifda faqat bitta oila saqlanadi. Premium orqali boshqa oilani qo‘shishingiz mumkin.';return}openFamily(c)}catch(e){err.textContent='Kirish rad etildi yoki Firebase ruxsati cheklangan.'}}
async function unlinkChild(row,id,name){const code=sessionStorage.getItem('family');if(!code||!auth.currentUser)return;if(!confirm(`${name} qurilmasi shu oiladan chiqarilsinmi?\n\nQurilma bloklanmaydi. Keyin oila kodi orqali qayta ulash mumkin.`))return;const b=row.querySelector('.child-unlink');if(b)b.disabled=true;try{await deleteDoc(doc(db,'families',code,'children',id));row.remove()}catch(e){console.error(e);if(b)b.disabled=false;alert('Qurilmani oiladan chiqarib bo‘lmadi. Internet yoki Firebase ruxsatini tekshiring.')}}
function wireChildDeleteButtons(){const list=$('childList');if(!list)return;list.querySelectorAll('.child').forEach(row=>{if(row.querySelector('.child-unlink'))return;const id=(row.querySelector('small')?.textContent||'').trim();if(!id)return;const name=(row.querySelector('b')?.textContent||'Farzand').trim();const fullId=row.dataset.childId||id;const b=document.createElement('span');b.className='child-unlink';b.setAttribute('role','button');b.setAttribute('tabindex','0');b.setAttribute('aria-label',`${name} qurilmasini oiladan chiqarish`);b.textContent='🗑';b.onclick=e=>{e.preventDefault();e.stopPropagation();unlinkChild(row,fullId,name)};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();unlinkChild(row,fullId,name)}};row.appendChild(b)})}
const childObserver=new MutationObserver(()=>wireChildDeleteButtons());childObserver.observe(document.body,{childList:true,subtree:true});
function boot(u){if(!u)return;if(sessionStorage.getItem('family')){setTimeout(wireChildDeleteButtons,0);return}render()}
onAuthStateChanged(auth,boot);
