import{getApps,initializeApp,getApp}from'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import{getAuth,onAuthStateChanged}from'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import{getFirestore,collection,query,where,getDocs,doc,getDoc,setDoc}from'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

const cfg={apiKey:'AIzaSyB72y9YkdCifEodbo2g_43FbbcDbvg0QF4',authDomain:'oilanazorat-3c8de.firebaseapp.com',projectId:'oilanazorat-3c8de',storageBucket:'oilanazorat-3c8de.firebasestorage.app',messagingSenderId:'1086556994078',appId:'1:1086556994078:web:5e576984e784d0bbdc4c0f'};
const app=getApps().length?getApp():initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
let booted=false;
const style=document.createElement('style');style.textContent=`#loginBtn{display:none!important}.pwa-family{margin-top:14px}.pwa-family .family-card{border:1px solid #e1e6ee;background:#fff;border-radius:16px;padding:15px;margin:9px 0}.pwa-family .family-card b{display:block;font-size:15px}.pwa-family .family-card small{display:block;color:#8993a2;margin:4px 0 10px}.pwa-family .family-card button,.pwa-family .secondary{width:100%;border:0;border-radius:12px;padding:12px;font-weight:850}.pwa-family .family-card button{background:#111827;color:#fff}.pwa-family .secondary{background:#eef2ff;color:#3856a8;margin-top:8px}.pwa-family .codebox{font-size:22px;letter-spacing:.16em;text-align:center;background:#f5f7fb;border:1px dashed #9aa7b8;border-radius:14px;padding:14px;margin:10px 0;font-weight:900}`;document.head.appendChild(style);
function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function makeCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<6;i++)s+=chars[Math.floor(Math.random()*chars.length)];return s}
function openFamily(code){sessionStorage.setItem('family',code);location.reload()}
function panel(){return $('codeScreen')?.querySelector('.card')}
function render(){const card=panel();if(!card)return;if(booted)return;booted=true;
 card.innerHTML=`<h2>Oila kodi</h2><p class="muted">Google hisobingizga ulangan oilalar avtomatik ko‘rsatiladi.</p><div id="pwaFamilies" class="pwa-family"><div class="loading">Oilalar tekshirilmoqda…</div></div>`;
 const box=$('pwaFamilies');
 box.innerHTML=`<button id="createFamily" class="primary">➕ Yangi oila kodi yaratish</button><button id="joinFamily" class="secondary">🔗 Mavjud oila kodini kiritish</button><div id="familyList" class="pwa-family"></div>`;
 $('createFamily').onclick=createFamily;
 $('joinFamily').onclick=()=>{box.innerHTML=`<h3>Mavjud oila kodi</h3><p class="muted">Android farzand qurilmasi ulangan oila kodini kiriting.</p><input id="pwaCode" class="code" maxlength="20" autocomplete="off" autocapitalize="characters" placeholder="AB12CD"><button id="pwaJoin" class="primary">Davom etish</button><p id="pwaErr" class="err"></p><button id="pwaBack" class="secondary">← Orqaga</button>`;$('pwaJoin').onclick=joinFamily;$('pwaBack').onclick=()=>renderFamilies()};
 renderFamilies();
}
async function renderFamilies(){const box=$('familyList');if(!box)return;const u=auth.currentUser;if(!u)return;box.innerHTML='<div class="loading">Mavjud oilalar yuklanmoqda…</div>';try{const snap=await getDocs(query(collection(db,'families'),where('ownerUid','==',u.uid)));if(snap.empty){box.innerHTML='<div class="empty">Hali sizga tegishli oila yaratilmagan.<br>Yuqoridagi tugma orqali yangi kod yarating.</div>';return}box.innerHTML='<h3 style="margin:18px 0 8px">Mening oilalarim</h3>';snap.forEach(d=>{const el=document.createElement('div');el.className='family-card';el.innerHTML=`<b>Oila kodi: ${esc(d.id)}</b><small>Farzandlar bilan bog‘langan oila</small><button>Oila panelini ochish →</button>`;el.querySelector('button').onclick=()=>openFamily(d.id);box.appendChild(el)})}catch(e){console.error(e);box.innerHTML='<div class="empty">Oilalarni avtomatik topib bo‘lmadi. Firebase ruxsatlarini tekshiring yoki mavjud kodni kiriting.</div>'}}
async function createFamily(){const u=auth.currentUser;if(!u)return;const b=$('createFamily');if(b)b.disabled=true;for(let i=0;i<8;i++){const code=makeCode();try{const ref=doc(db,'families',code),old=await getDoc(ref);if(old.exists())continue;await setDoc(ref,{ownerUid:u.uid,yaratilganMs:Date.now()});sessionStorage.setItem('family',code);const box=$('pwaFamilies');box.innerHTML=`<div class="family-card"><b>🎉 Yangi oila yaratildi</b><div class="codebox">${code}</div><small>Farzandingizning Android qurilmasida shu kod orqali oilaga ulang.</small><button id="openCreated">Farzandlarni ko‘rish →</button></div>`;$('openCreated').onclick=()=>location.reload();return}catch(e){console.error(e);if(b)b.disabled=false;box.innerHTML='<p class="err">Oila yaratilmadi: '+esc(e.message||'Firebase xatosi')+'</p><button class="primary" id="retryFamily">Qayta urinish</button>';if($('retryFamily'))$('retryFamily').onclick=createFamily;return}}if(b)b.disabled=false}
async function joinFamily(){const c=($('pwaCode')?.value||'').trim().toUpperCase(),err=$('pwaErr');if(!c){err.textContent='Oila kodini kiriting.';return}try{const s=await getDoc(doc(db,'families',c));if(!s.exists()){err.textContent='Oila kodi topilmadi.';return}const owner=s.data().ownerUid;if(owner&&owner!==auth.currentUser.uid){err.textContent='Bu oila kodi boshqa ota-onaga tegishli.';return}openFamily(c)}catch(e){err.textContent='Kirish rad etildi yoki Firebase ruxsati cheklangan.'}}
function boot(u){if(!u)return;if(sessionStorage.getItem('family'))return;render()}
onAuthStateChanged(auth,boot);
